version: '3'

services:
#flask-app
  python:
    build: .
    depends_on:
      - es
#elasticsearch
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2
    environment:
      - discovery.type=single-node                                  #Specifies whether Elasticsearch should form a multiple-node cluster.

  #nginx
  reverseproxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html                                        #where the static files are moved to
      - ./templates/index.html:/usr/share/nginx/html/index.html
    depends_on: 
      - python
    
networks: 
  elastic:
    driver: bridge
      
      #installs rules in the host machine so that containers on different bridge networks cannot communicate directly with each other.